# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "8.3.3"
    shell: /bin/bash --login -eo pipefail

    steps:
      - checkout

      # Set Ruby version
      - run:
          name: Set Ruby version
          command:  echo "ruby-2.4" > ~/.ruby-version

      # Update bundler
      - run:
          name: Update bundler
          command: bundle install

      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: bundle exec pod install

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: bundle exec fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: CircleCIDemo

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
